SAMS.Web/Areas/Admin/Models/Accessory/GetAccessoryCount.cs
using Abp.AutoMapper;
using SAMS.Accessories.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAMS.Web.Areas.Admin.Models.Accessory
{
    [AutoMapFrom(typeof(GetAccessoryDto))]
    public class GetAccessoryCount: GetAccessoryDto
    {
        public int Count { get; set; }
    }
}

SAMS.Web/Areas/Admin/Models/Accessory/GetNewAccessoryUseViewModel.cs
using Abp.Application.Services.Dto;
using SAMS.WorkOrders.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAMS.Web.Areas.Admin.Models.Accessory
{
    public class GetNewAccessoryUseViewModel
    {
        public PagedResultDto<GetNewAccessoryUseDto> Accessories { get; set; }
        public int PageIndex { get; set; }
        public int PageSize { get; set; }
        public int Start
        {
            get
            {
                return (PageIndex - 1) * PageSize + 1;
            }
        }

        public int End
        {
            get
            {
                int end = Start + PageSize - 1;
                if (end > Accessories.TotalCount) end = Accessories.TotalCount;
                return end;
            }
        }
        public int PageCount
        {
            get
            {
                return (int)Math.Ceiling((double)Accessories.TotalCount / (double)PageSize);
            }
        }
        public List<int> PageNumbers
        {
            get
            {
                int step = 5;//偏移量
                int leftNum = 0;//左边界
                int rightNum = 0;//右边界


                if (PageIndex - step < 1)
                {
                    leftNum = 1;
                }
                else
                {
                    leftNum = PageIndex - step;
                }
                if (PageIndex + step > PageCount)
                {
                    rightNum = PageCount;
                }
                else
                {
                    rightNum = PageIndex + step;
                }

                var list = new List<int>();

                for (int i = leftNum; i <= rightNum; i++)
                {
                    list.Add(i);
                }

                return list;

            }
        }
    }
}

SAMS.Web/Areas/Admin/Models/Accessory/GetNewAccessoryViewModel.cs
using Abp.Application.Services.Dto;
using SAMS.Accessories.Dtos;
using SAMS.Inventory.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAMS.Web.Areas.Admin.Models.Accessory
{
    public class GetNewAccessoryViewModel
    {
        public string Type { get; set; }
        public PagedResultDto<GetAccessoryCount> Accessories { get; set; }
        public int PageIndex { get; set; }
        public int PageSize { get; set; }
        public int Start
        {
            get
            {
                return (PageIndex - 1) * PageSize + 1;
            }
        }

        public int End
        {
            get
            {
                int end = Start + PageSize - 1;
                if (end > Accessories.TotalCount) end = Accessories.TotalCount;
                return end;
            }
        }
        public int PageCount
        {
            get
            {
                return (int)Math.Ceiling((double)Accessories.TotalCount / (double)PageSize);
            }
        }
        public List<int> PageNumbers
        {
            get
            {
                int step = 5;//偏移量
                int leftNum = 0;//左边界
                int rightNum = 0;//右边界


                if (PageIndex - step < 1)
                {
                    leftNum = 1;
                }
                else
                {
                    leftNum = PageIndex - step;
                }
                if (PageIndex + step > PageCount)
                {
                    rightNum = PageCount;
                }
                else
                {
                    rightNum = PageIndex + step;
                }

                var list = new List<int>();

                for (int i = leftNum; i <= rightNum; i++)
                {
                    list.Add(i);
                }

                return list;

            }
        }
    }
}

SAMS.Web/Areas/Admin/Models/Accessory/GetNewExportEnterStockOrderViewModel.cs
using Abp.Application.Services.Dto;
using SAMS.Inventory.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAMS.Web.Areas.Admin.Models.Accessory
{
    public class GetNewExportEnterStockOrderViewModel
    {
        public PagedResultDto<StockBillHeadDto> Orders { get; set; }
        public int PageIndex { get; set; }
        public int PageSize { get; set; }
        public int Start
        {
            get
            {
                return (PageIndex - 1) * PageSize + 1;
            }
        }

        public int End
        {
            get
            {
                int end = Start + PageSize - 1;
                if (end > Orders.TotalCount) end = Orders.TotalCount;
                return end;
            }
        }
        public int PageCount
        {
            get
            {
                return (int)Math.Ceiling((double)Orders.TotalCount / (double)PageSize);
            }
        }
        public List<int> PageNumbers
        {
            get
            {
                int step = 5;//偏移量
                int leftNum = 0;//左边界
                int rightNum = 0;//右边界


                if (PageIndex - step < 1)
                {
                    leftNum = 1;
                }
                else
                {
                    leftNum = PageIndex - step;
                }
                if (PageIndex + step > PageCount)
                {
                    rightNum = PageCount;
                }
                else
                {
                    rightNum = PageIndex + step;
                }

                var list = new List<int>();

                for (int i = leftNum; i <= rightNum; i++)
                {
                    list.Add(i);
                }

                return list;

            }
        }
    }
}

SAMS.Web/Areas/Admin/Models/Accessory/NewExportEnterStockOrderDetailViewModel.cs
using SAMS.Inventory.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAMS.Web.Areas.Admin.Models.Accessory
{
    public class NewExportEnterStockOrderDetailViewModel
    {
        public StockBillDto bill { get; set; }
       
    }
}

SAMS.Web/Areas/StaffMobile/Models/AccessoryViewModel.cs
using Abp.Application.Services.Dto;
using SAMS.Inventory.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAMS.Web.Areas.StaffMobile.Models
{
    public class AccessoryViewModel
    {
        public ListResultDto<StaffStockDto> MyAccessories { get; set; }
    }
}

SAMS.Web/Areas/Admin/Controllers/AccessoryController.cs
using Abp.Application.Services.Dto;
using Abp.AutoMapper;
using Abp.Web.Mvc.Authorization;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SAMS.Accessories;
using SAMS.Accessories.Dtos;
using SAMS.Inventory;
using SAMS.Inventory.Dto;
using SAMS.Users;
using SAMS.Web.Areas.Admin.Models.Accessory;
using SAMS.Web.Areas.Admin.Models.Common;
using SAMS.Web.Areas.Admin.Models.WorkOrder;
using SAMS.Web.Controllers;
using SAMS.WorkOrders;
using SAMS.WorkOrders.Dtos;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SAMS.Web.Areas.Admin.Controllers
{
    [AbpMvcAuthorize(Roles ="Admin")]
    public class AccessoryController : SAMSControllerBase
    {
        private readonly IInventoryAppService _inventoryAppService;
        private readonly IAccessoryAppService _accessoryAppService;
        private readonly IWorkOrderAppService _workOrderAppService;
        private readonly UserManager _userManager;
        public AccessoryController(IInventoryAppService inventoryAppService, IAccessoryAppService accessoryAppService,
            IWorkOrderAppService workOrderAppService ,UserManager userManager)
        {
            _inventoryAppService = inventoryAppService;
            _accessoryAppService = accessoryAppService;
            _workOrderAppService = workOrderAppService;
            _userManager = userManager;
        }
        // GET: Admin/Accessory
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult NewOrgStock()
        {
            return View();
        }

        /// <summary>
        /// 备件入库
        /// </summary>
        /// <param name="type"></param>
        /// <returns></returns>
        public ActionResult CreateNewEnterStockOrder(string type)
        {
            ViewBag.Type = type;
            if (type.Equals("EnterStockNew"))
            {
                ViewBag.CategoryID = 2;//系统入库
                ViewBag.Title = "备件入库";
                ViewBag.UserList = null;


            }
            else if (type.Equals("StaffRefundNew"))
            {
                ViewBag.Title = "员工退料";
                ViewBag.CategoryID = 4;//员工退料
                var users = _userManager.Users.ToList();
                var userList = new SelectList(users, "ID", "Name");
                ViewBag.UserList = userList;
            }

            ViewBag.StockType = 2;//入库
            return View();
        }
        /// <summary>
        /// 备件出库
        /// </summary>
        /// <param name="type">ExportStockNew 、StaffPickingNew</param>
        /// <returns></returns>
        public ActionResult CreateNewExportStockOrder(string type)
        {
            ViewBag.Type = type;
            if (type.Equals("ExportStockNew"))
            {
                ViewBag.Title = "备件出库";
                ViewBag.CategoryID = 1;//系统出库
                ViewBag.UserList = null;
            }
            else if (type.Equals("StaffPickingNew"))
            {
                ViewBag.Title = "员工领料";
                var users = _userManager.Users.ToList();
                var userList = new SelectList(users, "ID", "Name");
                ViewBag.UserList = userList;
                ViewBag.CategoryID = 3;//员工领料
            }
            ViewBag.StockType = 1;//出库
            return View();
        }
        public PartialViewResult SelectNewAccessory(string type, long? staffId)
        {
            ViewBag.Type = type;
            if (staffId.HasValue)
                ViewBag.StaffId = staffId.Value;
            else
                ViewBag.StaffId = "";
            return PartialView("_SelectNewAccessory");
        }
        public PartialViewResult GetNewAccessory(GetAccessoryListParam param)
        {
            string type = param.Type;
            int skipCount = param.PageSize * (param.PageIndex - 1);
            string sorting = null;
            if (!string.IsNullOrEmpty(param.Sort))
                sorting = param.Sort + " " + param.Direction;
            var viewModel = new GetNewAccessoryViewModel();

            //配件入库          
            if (type.Equals("EnterStockNew"))
            {   
                
                GetAccessoryInput input = new GetAccessoryInput() { MaxResultCount = param.PageSize, SkipCount = skipCount, Sorting = sorting};
                if (((string)(JObject.Parse(param.Where)["searchkey"])) != "")
                {
                    JObject jsob = JObject.Parse(param.Where);
                    string jval = (string)jsob["searchkey"];

                    input = new GetAccessoryInput() { MaxResultCount = 1000, SkipCount = skipCount, Sorting = sorting };
                    var accessoryList = _accessoryAppService.GetAccessory(input);
                    viewModel.Accessories = new PagedResultDto<GetAccessoryCount>
                    {
                        Items = accessoryList.Items.Where(x => x.AccessoryNumber.Contains(jval)).Select(x => new GetAccessoryCount
                        {
                            AccessoryId = x.AccessoryId,
                            AccessoryName = x.AccessoryName,
                            AccessoryModel = x.AccessoryModel,
                            AccessoryNumber = x.AccessoryNumber,
                            AccessoryUnit = x.AccessoryUnit,
                            Count = 0
                        }
                        )
                        .ToList(),
                        TotalCount = accessoryList.TotalCount,

                    };

                }
                else {

                    var accessoryList = _accessoryAppService.GetAccessory(input);
                    viewModel.Accessories = new PagedResultDto<GetAccessoryCount>
                    {
                        Items = accessoryList.Items.Select(x => new GetAccessoryCount
                        {
                            AccessoryId = x.AccessoryId,
                            AccessoryName = x.AccessoryName,
                            AccessoryModel = x.AccessoryModel,
                            AccessoryNumber = x.AccessoryNumber,
                            AccessoryUnit = x.AccessoryUnit,
                            Count = 0
                        }
                        )
                        .ToList(),
                        TotalCount = accessoryList.TotalCount,

                    };



                }

            }
            else if (type.Equals("StaffRefundNew"))//员工退料
            {
                long staffID = param.StaffID.Value;
                GetNewStaffStockInput input = new GetNewStaffStockInput() { MaxResultCount = param.PageSize, SkipCount = skipCount, Sorting = sorting, StaffID = staffID };

                var accessoryList = _inventoryAppService.GetStaffStock(input);
                viewModel.Accessories = new PagedResultDto<GetAccessoryCount>
                {
                    Items = accessoryList.Items.Select(x => new GetAccessoryCount
                    {
                        AccessoryId = x.AccessoryId,
                        AccessoryName = x.AccessoryName,
                        AccessoryModel = x.AccessoryModel,
                        AccessoryNumber = x.AccessoryNumber,
                        AccessoryUnit = x.AccessoryUnit,
                        Count = x.Count
                    }
                    )
                    .ToList(),
                    TotalCount = accessoryList.TotalCount,

                };
            }
            else if (type.Equals("StaffPickingNew"))//员工领料
            {
                // long staffID = param.StaffID.Value;

                GetOrgStockInput input = new GetOrgStockInput() { MaxResultCount = param.PageSize, SkipCount = skipCount, Sorting = sorting };
                var accessoryList = _inventoryAppService.GetOrgStock(input);
                viewModel.Accessories = new PagedResultDto<GetAccessoryCount>
                {
                    Items = accessoryList.Items.Select(x => new GetAccessoryCount
                    {
                        AccessoryId = x.AccessoryId,
                        AccessoryName = x.AccessoryName,
                        AccessoryModel = x.AccessoryModel,
                        AccessoryNumber = x.AccessoryNumber,
                        AccessoryUnit = x.AccessoryUnit,
                        Count = x.Count
                    }
                   )
                   .ToList(),
                    TotalCount = accessoryList.TotalCount,

                };
            }
            else if (type.Equals("ExportStockNew"))//配件出库
            {
                GetOrgStockInput input = new GetOrgStockInput() { MaxResultCount = param.PageSize, SkipCount = skipCount, Sorting = sorting };
                var accessoryList = _inventoryAppService.GetOrgStock(input);
                viewModel.Accessories = new PagedResultDto<GetAccessoryCount>
                {
                    Items = accessoryList.Items.Select(x => new GetAccessoryCount
                    {
                        AccessoryId = x.AccessoryId,
                        AccessoryName = x.AccessoryName,
                        AccessoryModel = x.AccessoryModel,
                        AccessoryNumber = x.AccessoryNumber,
                        AccessoryUnit = x.AccessoryUnit,
                        Count = x.Count
                    }
                   )
                   .ToList(),
                    TotalCount = accessoryList.TotalCount,

                };
            }
            viewModel.Type = type;
            viewModel.PageIndex = param.PageIndex;
            viewModel.PageSize = param.PageSize;
            return PartialView("_GetNewAccessory", viewModel);
        }
        public PartialViewResult GetNewOrgStock(GetListParam param)
        {
            int skipCount = param.PageSize * (param.PageIndex - 1);
            string sorting = null;

SAMS.Web/Controllers/AccessoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAMS.Web.Controllers
{
    public class AccessoryController : Controller
    {
        // GET: Accessory
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult NewOrgStock()
        {
            return View();
        }
    }
}

SAMS.Web/Areas/Admin/Views/Accessory/NewAccessoryUse.cshtml
@{
    ViewBag.Title = "NewAccessoryUse";
    Layout = "~/Areas/Admin/Views/Layout/_Layout.cshtml";
}

               <!-- BEGIN PAGE CONTENT-->
<div class="row">

    <div class="col-md-12">

        <div class="side-menu-sidebar ">
            <div class="scroller">
                <div class="portlet portlet-nav">
                    <div class="portlet-title">
                        <div class="caption" data-toggle="collapse" data-target="#lst1">
                            <span class="uppercase">备件管理</span>
                            <a href="javascript:;" class="caption-helper visible-sm-inline-block visible-xs-inline-block">单击展示列表</a>
                        </div>
                        <div class="btn-group pull-right esh-set-btn-group">
                            <a href="javascript:;" class="esh-set-group" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa  fa-angle-down"></i>
                            </a>
                            <ul class="esh-pub-menu dropdown-menu pull-right">
                                <li>
                                    <a href="/admin/accessorysetting">
                                        备件设置
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="portlet-body side-menu-project-list-content" id="lst1">
                        <div class="side-menu-project-list" data-always-visible="1" data-rail-visible1="1">
                            <ul class="nav nav-pills nav-stacked">
                                <li class="">
                                    <a href=/admin/accessory/neworgstock>备件库存</a>
                                </li>
                                <li class="">
                                    <a href=/admin/accessory/newexportenterstockorder>备件出入库单</a>
                                </li>
                                <li class="">
                                    <a href=/admin/accessory/newstaffpicking>员工领用备件情况</a>
                                </li>
                                <li class="active">
                                    <a href=/admin/accessory/newaccessoryuse>备件使用明细</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="side-menu-content">
            <div class="portlet light">
                <div class="portlet-title">
                    <div class="caption title">
                        备件使用明细
                    </div>
                    <div class="input-group pull-right">
                        <div class="input-group input-medium ">
                            <input class="form-control" id="workOrderNumber" maxlength="50" name="workOrderNumber" placeholder="输入工单编号..." type="text" value="" />
                            <span class="input-group-btn">
                                <button class="btn green" id="btnSearch" type="button"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="col-md-6 col-xs-6 clear-padding-left">
                            <button class="btn green collapse" id="btnFilter">筛选</button>
                        </div>
                        <div class="col-md-6 col-xs-6 clear-padding-right">
                            <div class="pull-right">
                                <div class="btn-group">
                                    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                                        更多操作&nbsp;<i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a data-toggle="modal" href="javascript:void(0)" onclick="exportExcel()">Excel导出 </a>
                                        </li>
                                    </ul>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                    <div class="esh-table-filter" id="filterContent">
                        <ul class="esh-region-color">
                            <li class="esh-filter-item clearfix">
                                <span>服务人员：</span>
                                <ul class="filter-option">
                                    <li class="wipper select">
                                        <select class="form-control" id="select-staffId">
                                            <option value="">请选择服务人员</option>
                                            <option value="000c872e-c238-4bf4-986f-2e9d5fc2e079">张工</option>
                                            <option value="55d87af7-e020-485a-ac6a-f9e1e8a712ee">李工</option>
                                            <option value="953dc607-d48e-4d9f-9d83-53139fb17ea5">13561899216</option>
                                        </select>
                                    </li>
                                </ul>
                            </li>
                            <li class="esh-filter-item clearfix">
                                <span>使用日期：</span>
                                <ul class="filter-option input-daterange date-picker">
                                    <li class="wipper">
                                        <input class="form-control" id="startDate" name="startDate" onblur="clearDate(this)" placeholder="开始日期" type="text" value="" />
                                    </li>
                                    <li>至</li>
                                    <li class="wipper">
                                        <input class="form-control" id="endDate" name="endDate" onblur="clearDate(this)" placeholder="结束日期" type="text" value="" />
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div id="dataTable" class="dataTables_wrapper no-footer">
                        @Html.Action("GetNewAccessoryUse", "Accessory", new { PageIndex = 1, PageSize = 10 ,Where="{}"})
                    </div>
                </div>

                <form action="/admin/accessory/getnewaccessoryuse" data-ajax="true" data-ajax-begin="showLoading" data-ajax-complete="hideLoading" data-ajax-failure="showException" data-ajax-mode="replace" data-ajax-success="initTable" data-ajax-update="#dataTable" id="searchByRequest" method="post"><input id="PageIndex" name="PageIndex" type="hidden" value="1" /><input data-val="true" data-val-number="字段 PageSize 必须是一个数字。" data-val-required="The PageSize field is required." id="PageSize" name="PageSize" type="hidden" value="10" /><input id="Sort" name="Sort" type="hidden" value="" /><input id="Direction" name="Direction" type="hidden" value="" /><input id="Where" name="Where" type="hidden" value="" /></form>
            </div>
        </div>
    </div>

</div>
<!-- END PAGE CONTEN -->
          

SAMS.Web/Areas/Admin/Views/Accessory/_GetNewAccessory.cshtml
@model SAMS.Web.Areas.Admin.Models.Accessory.GetNewAccessoryViewModel
<div class="table-scrollable">
    <table class="table  dataTable table-bordered" id="tableList">
        <thead>
            <tr>
                <th class="hidden">id</th>
                <th style="width:100px;">
                    备件编码
                </th>
                <th style="min-width:70px;">
                    名称
                </th>
                <th style="min-width:70px;">
                    规格
                </th>
                <th style="width:40px;">
                    单位
                </th>
                <th class="@(Model.Type.Equals("StaffRefundNew")? "": "hidden")"  style="width:40px;">
                    @(Model.Type.Equals("StaffRefundNew")? "持有数量": "当前库存")
                </th>
               

                <th style="width:70px;">
                    操作
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Accessories.Items)
            {
                <tr class="odd gradeX">
                    <td class="hidden" name="Id">@item.AccessoryId</td>
                   
                    <td  name="Number">
                        @item.AccessoryNumber
                    </td>

                    <td name="Name">@item.AccessoryName</td>
                    <td name="Spec">
                        @item.AccessoryModel
                    </td>
                    <td name="Unit">@item.AccessoryUnit</td>
                  
                    <td class="@(Model.Type.Equals("StaffRefundNew")? "": "hidden")" name="Count">
                       @item.Count
                    </td>
                   
                    <td>
                       
                        <button onclick="select_accessory('{&quot;ID&quot;:&quot;@item.AccessoryId &quot;,&quot;Number&quot;:&quot;@item.AccessoryNumber&quot;,&quot;Count&quot;:@item.Count,&quot;Name&quot;:&quot;@item.AccessoryName&quot;,&quot;Model&quot;:&quot;@item.AccessoryModel&quot;,&quot;Unit&quot;:&quot;@item.AccessoryUnit&quot;}')" 
                                class="btn btn-default btn-xs black">
                            <i class="fa fa-check"></i>选择
                        </button>
                    </td>
                    
                </tr>
            }
          
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col-md-5 col-sm-5">
        <div class="dataTables_info" id="tableListInfo" role="status" aria-live="polite">
            @if(Model.Accessories.TotalCount>0)
            {
            <lable>@Model.Start - @Model.End 条记录&nbsp;&nbsp;&nbsp;&nbsp;共 @Model.Accessories.TotalCount 条</lable>
            }
            else
            {
                <label>没有查询到所需数据</label>
            }
        </div>
    </div>
    <div class="col-md-7 col-sm-7">
        <div class="dataTables_paginate paging_bootstrap_full_number">
@if(Model.Accessories.TotalCount > 0)
{
            <ul class="pagination">
                @if (Model.PageIndex == 1)
                {
                    <li class='disabled prev'>
                        <a href='javascript:void(0)'>
                            <i class='fa fa-angle-double-left'></i>
                        </a>
                    </li>
                        <li class="disabled prev"><a href="javascript:void(0);"><i class='fa fa-angle-left'></i></a></li>
                }
                else
                {
                    <li class="prev"><a href="#" title="首页" onclick="changePageIndex(1)"><i class='fa fa-angle-double-left'></i></a></li>
                        <li class="prev"><a href="#" title="上一页" onclick="changePageIndex(@Model.PageIndex -1)"><i class='fa fa-angle-left'></i></a></li>
                }

                @foreach (var i in Model.PageNumbers)
                {
                    if (Model.PageIndex.Equals(i))
                    {
                        <li class="active"><a href="#" onclick="changePageIndex(@i)">@(i.ToString())</a></li>
                    }
                    else
                    {
                        <li><a href="#" onclick="changePageIndex(@(i.ToString()))">@(i.ToString())</a></li>
                    }


                }

                @if (Model.PageIndex == Model.PageCount)
                {
                    <li class="disabled next">
                        <a href="#" title="下一页" onclick="changePageIndex(@(Model.PageIndex + 1 ))">
                            <i class='fa fa-angle-right'></i>
                        </a>
                    </li>
                        <li class="disabled next">
                            <a href="#" title="末页" onclick="changePageIndex(@Model.PageCount )">
                                <i class='fa fa-angle-double-right'></i>
                            </a>
                        </li>
                }
                else
                {
                    <li class="next">
                        <a href="#" title="下一页" onclick="changePageIndex(@(Model.PageIndex + 1 ))">
                            <i class='fa fa-angle-right'></i>
                        </a>
                    </li>
                        <li class="next">
                            <a href="#" title="末页" onclick="changePageIndex(@Model.PageCount )">
                                <i class='fa fa-angle-double-right'></i>
                            </a>
                        </li>
                }
            </ul>
}
        </div>
    </div>

</div>